sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t squad-health-check-tests .
    - stage: Run tests
      script: docker run -it squad-health-check-tests